[[rows]]
keys = [
  { normal = "Esc" },
  { normal = "F1", width = 0.875 },
  { normal = "F2", width = 0.875 },
  { normal = "F3", width = 0.875 },
  { normal = "F4", width = 0.875 },
  { normal = "F5", width = 0.875 },
  { normal = "F6", width = 0.875 },
  { normal = "F7", width = 0.875 },
  { normal = "F8", width = 0.875 },
  { normal = "F9", width = 0.875 },
  { normal = "F10", width = 0.875 },
  { normal = "F11", width = 0.875 },
  { normal = "F12", width = 0.875 },
  { normal = "Pause", width = 0.875 },
  { normal = "Prt\nSc", width = 0.875 },
  { normal = "Ins", width = 0.875 },
  { normal = "Del", width = 0.875 },
]

[[rows]]
keys = [
  { normal = "全/半" },
  { normal = "1", shift = "!" },
  { normal = "2", shift = "\"" },
  { normal = "3", shift = "#" },
  { normal = "4", shift = "$" },
  { normal = "5", shift = "%" },
  { normal = "6", shift = "&" },
  { normal = "7", shift = "'" },
  { normal = "8", shift = "(" },
  { normal = "9", shift = ")" },
  { normal = "0", shift = "" },
  { normal = "-", shift = "=" },
  { normal = "^", shift = "~" },
  { normal = "\\", shift = "|" },
  { normal = "BS" },
]


[[rows]]
keys = [
  { normal = "TAB", width = 1.5 },
  { normal = "q", shift = "Q" },
  { normal = "w", shift = "W" },
  { normal = "e", shift = "E" },
  { normal = "r", shift = "R" },
  { normal = "t", shift = "T" },
  { normal = "y", shift = "Y" },
  { normal = "u", shift = "U" },
  { normal = "i", shift = "I" },
  { normal = "o", shift = "O" },
  { normal = "p", shift = "P" },
  { normal = "@", shift = "`" },
  { normal = "[", shift = "{" },
  { normal = "Enter", height = 2, width = 1.5 },
]

[[rows]]
keys = [
  { normal = "CAPS", width = 1.5 },
  { normal = "a", shift = "A" },
  { normal = "s", shift = "S" },
  { normal = "d", shift = "D" },
  { normal = "f", shift = "F" },
  { normal = "g", shift = "G" },
  { normal = "h", shift = "H" },
  { normal = "j", shift = "J" },
  { normal = "k", shift = "K" },
  { normal = "l", shift = "L" },
  { normal = ";", shift = "+" },
  { normal = ":", shift = "*" },
  { normal = "]", shift = "}" },
]

[[rows]]
keys = [
  { normal = "Shift", width = 2 },
  { normal = "z", shift = "Z" },
  { normal = "x", shift = "X" },
  { normal = "c", shift = "C" },
  { normal = "v", shift = "V" },
  { normal = "b", shift = "B" },
  { normal = "n", shift = "N" },
  { normal = "m", shift = "M" },
  { normal = ",", shift = "<" },
  { normal = ".", shift = ">" },
  { normal = "/", shift = "?" },
  { normal = "\\", shift = "_" },
  { normal = "↑" },
  { normal = "Shift" },
]

[[rows]]
keys = [
  { normal = "Ctrl", width = 1 },
  { normal = "Super" },
  { normal = "Alt" },
  { normal = "無変換" },
  { normal = "Space", width = 3 },
  { normal = "変換" },
  { normal = "かな\nカナ" },
  { normal = "Alt" },
  { normal = "App" },
  { normal = "Ctrl", width = 1 },
  { normal = "←" },
  { normal = "↓" },
  { normal = "→" },
]
