[[rows]]
keys = [
  { normal = "1", shift = "!" },
  { normal = "2", shift = "\"" },
  { normal = "3", shift = "#" },
  { normal = "4", shift = "$" },
  { normal = "5", shift = "%" },
  { normal = "6", shift = "&" },
  { normal = "7", shift = "'" },
  { normal = "8", shift = "(" },
  { normal = "9", shift = ")" },
  { normal = "0", shift = "" },
  { normal = "-", shift = "=" },
  { normal = "^", shift = "~" },
  { normal = "\\", shift = "|" }
]

[[rows]]
keys = [
  { normal = "q", shift = "Q" },
  { normal = "w", shift = "W" },
  { normal = "e", shift = "E" },
  { normal = "r", shift = "R" },
  { normal = "t", shift = "T" },
  { normal = "y", shift = "Y" },
  { normal = "u", shift = "U" },
  { normal = "i", shift = "I" },
  { normal = "o", shift = "O" },
  { normal = "p", shift = "P" },
  { normal = "@", shift = "`" },
  { normal = "[", shift = "{" },
  { normal = "", shift = "" }
]

[[rows]]
keys = [
  { normal = "a", shift = "A" },
  { normal = "s", shift = "S" },
  { normal = "d", shift = "D" },
  { normal = "f", shift = "F" },
  { normal = "g", shift = "G" },
  { normal = "h", shift = "H" },
  { normal = "j", shift = "J" },
  { normal = "k", shift = "K" },
  { normal = "l", shift = "L" },
  { normal = ";", shift = "+" },
  { normal = ":", shift = "*" },
  { normal = "]", shift = "}" },
  { normal = "", shift = "" }
]

[[rows]]
keys = [
  { normal = "z", shift = "Z" },
  { normal = "x", shift = "X" },
  { normal = "c", shift = "C" },
  { normal = "v", shift = "V" },
  { normal = "b", shift = "B" },
  { normal = "n", shift = "N" },
  { normal = "m", shift = "M" },
  { normal = ",", shift = "<" },
  { normal = ".", shift = ">" },
  { normal = "/", shift = "?" },
  { normal = "\\", shift = "_" },
  { normal = "", shift = "" },
  { normal = "", shift = "" }
]
