name: Check

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Check formatting
        run: nix develop --command cargo fmt --all -- --check

      - name: Check
        run: nix develop --command cargo check --all-targets

      - name: Clippy
        run: nix develop --command cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: nix develop --command cargo test --all